version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8001:8000"
    environment:
      - AWX_BASE_URL=http://192.168.122.46:31366
      - AWX_USERNAME=openwebui
      - AWX_PASSWORD=openwebui
      - AUDIT_LOG_DIR=/var/log/mcp
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - LLM_MODEL=gpt-4o
      - LLM_ENDPOINT="http://host.docker.internal:11434"
    volumes:
      - ./logs:/var/log/mcp
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
