# PersistentVolumeClaim for audit logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
